CREATE TABLE CAR
(
	ID           BIGINT PRIMARY KEY,
	REGISTRATION VARCHAR(64) NOT NULL UNIQUE,
	BRAND        VARCHAR(64) NOT NULL,
	MODEL        VARCHAR(64) NOT NULL
);

CREATE SEQUENCE CAR_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

CREATE TABLE PARKING_SPOT
(
	ID     BIGINT PRIMARY KEY,
	NUMBER VARCHAR(64) NOT NULL UNIQUE,
	NAME   VARCHAR(64) NOT NULL
);

CREATE SEQUENCE PARKING_SPOT_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;


CREATE TABLE RESERVATION
(
	ID              BIGINT PRIMARY KEY,
	CAR_ID          BIGINT REFERENCES CAR (ID),
	PARKING_SPOT_ID BIGINT REFERENCES PARKING_SPOT (ID),
	CREATE_DATE     TIMESTAMP NOT NULL,
	FROM_DATE       TIMESTAMP NOT NULL,
	TO_DATE         TIMESTAMP NOT NULL
);

CREATE SEQUENCE RESERVATION_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

