INSERT INTO PARKING_SPOT (ID, NUMBER, NAME)
VALUES (1, 'NX-10', 'Back');

INSERT INTO PARKING_SPOT (ID, NUMBER, NAME)
VALUES (2, 'NX-11', 'Front');

INSERT INTO PARKING_SPOT (ID, NUMBER, NAME)
VALUES (3, 'NX-12', 'Left');

INSERT INTO PARKING_SPOT (ID, NUMBER, NAME)
VALUES (4, 'NX-13', 'Right');
